services:
  router:
    build: ./Router
    restart: unless-stopped

  order-manager:
    build: ./OrderManager
    restart: unless-stopped

  instrument-manager:
    build: ./InstrumentManager
    restart: unless-stopped
  chart-loader:
    build: ./ChartLoader
    restart: unless-stopped

  frontend:
    build: ./Frontend
    restart: unless-stopped

  redis-db:
    image: redis:latest
    volumes:
      - ./redisdata:/data
    restart: unless-stopped

  nginx:
    build: ./Nginx
    ports: 
      - "80:80"
    depends_on:
      - router
      - frontend
    restart: unless-stopped