FROM python:3.13.2-slim

WORKDIR /app

COPY src/requirements.txt ./

RUN pip install -r requirements.txt --no-cache-dir

COPY src /app
 
EXPOSE 8084
CMD [ "python", "-m", "uvicorn", "chart_loader:app", "--host", "0.0.0.0", "--port", "8084" ]