FROM python:3.13.2-slim

WORKDIR /app

COPY src/requirements.txt ./

RUN pip install -r requirements.txt --no-cache-dir

COPY src /app
 
EXPOSE 8083
CMD [ "python", "-m", "uvicorn", "instrument_manager:app", "--host", "0.0.0.0", "--port", "8083" ]